/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.cecatto.urlshortener;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class App {

  public static void main(String[] args) {
    var application = new SpringApplication(App.class);
    try {
      application.run(args);
    } catch (Exception e) {
      e.printStackTrace();
    }
  }
}
